version: '3.8'

services:
  # The FastAPI Application Service
  app:
    build: .
    container_name: movie_app
    ports:
      - "8000:8000"  
    volumes:
      - .:/app      
    env_file:
     - .env
    depends_on:
      - db

  # The PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: movie_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: movie_rating_db
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: